### ISSUE TITLE
[FEATURE] Support worker status recover after restart

### ISSUE THREAD

**Issue by AngersZhuuuu** [alibaba/RemoteShuffleService#320]
### Is your feature request related to a problem? Please describe.
https://docs.google.com/document/d/1-kwoQ0DofuTG8nA9DKC5Pz0idDDHL-5n_G1TRhVwnBU/edit#heading=h.ppikr69abcj2

### Describe the solution you'd like

- [x] [[1] Worker trigger shutdown hook when run command `stop-worker.sh`](https://github.com/alibaba/RemoteShuffleService/issues/321)
- [x] [[2] After stopping worker, reject reserve slot request. ](https://github.com/alibaba/RemoteShuffleService/issues/364)
- [x] [[3] Stop worker after all PartitionLocation is removed](https://github.com/alibaba/RemoteShuffleService/issues/322)
- [x] [[4] Shutdown PartitionSorter should graceful shutdown](https://github.com/alibaba/RemoteShuffleService/issues/360)
- [x] [[5] Extract Partition's file name/length/ChunkOffset FileInfo trait from FileWriter](https://github.com/alibaba/RemoteShuffleService/issues/323)
- [x] [[6] FileInfo support recover from LevelDB](https://github.com/alibaba/RemoteShuffleService/issues/362)
- [x] [[7] Master should handle registered worker with same port](https://github.com/alibaba/RemoteShuffleService/issues/367) 
- [x] [[8] RetryingChunkClient openChunks failed should wait](https://github.com/alibaba/RemoteShuffleService/issues/385)
- [x] [[9] Refactor code](https://github.com/alibaba/RemoteShuffleService/issues/412) 
- [x] [[10] Restart scrip to quickly start worker after stop](https://github.com/alibaba/RemoteShuffleService/issues/388)
- [x] [[11] Doc about worker recover usage](https://github.com/alibaba/RemoteShuffleService/issues/387)

Related BUG fix

- [[BUG] Add synchronization to FileInfo and workingDirWriters to fix concurrent issues](https://github.com/alibaba/RemoteShuffleService/issues/407)
- [[BUG] Worker RPC conf not work](https://github.com/alibaba/RemoteShuffleService/issues/418)
- [[BUG] Make sure before sort file, sortedFile and indexFile is empty](https://github.com/alibaba/RemoteShuffleService/issues/457)
- [[BUG] Should sync update sortingFiles and sortedFiles](https://github.com/alibaba/RemoteShuffleService/issues/493)

### Describe alternatives you've considered

/cc @who-need-to-know

/assign @who-can-help-you
